version: '3.8'

services:
  # Ollama - Motor de IA Local
  ollama:
    image: ollama/ollama:latest
    container_name: Ollama_IA_LOCAL
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./training_data:/training_data  # Para dados de treinamento
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped
    networks:
      - jarvis_network

  # Open WebUI - Interface Web tipo ChatGPT
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: Jarvis_WebUI
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=sua_chave_secreta_aqui
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - jarvis_network

  # Jupyter Notebook - Para treinamento e experimentos
  jupyter:
    image: jupyter/tensorflow-notebook:latest
    container_name: Jarvis_Training
    ports:
      - "8888:8888"
    volumes:
      - ./training_notebooks:/home/jovyan/work
      - ./training_data:/home/jovyan/training_data
      - ./models:/home/jovyan/models
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=jarvis2025
    restart: unless-stopped
    networks:
      - jarvis_network

volumes:
  ollama_data:
  open_webui_data:

networks:
  jarvis_network:
    driver: bridge
