# docker-compose.yml compatível com Compose v2+
services:
  core:
    build:
      context: .
      dockerfile: ./docker/core/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./memory:/app/memory
      - ./config:/app/config
      - ./frontend:/app/frontend
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - whisper
      - tts
  whisper:
    build:
      context: .
      dockerfile: ./docker/whisper/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
  tts:
    build:
      context: ./docker/tts
    ports:
      - "5002:5002"
    environment:
      - PYTHONUNBUFFERED=1
