version: '3.8'

services:
  core:
    build:
      context: .
      dockerfile: ./docker/core/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./memory:/app/memory
      - ./config:/app/config
      - ./frontend:/app/frontend
      - jarvis_logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TTS_SERVICE_URL=http://tts:5002
      - STT_SERVICE_URL=http://whisper:5001
    depends_on:
      tts:
        condition: service_healthy
      whisper:
        condition: service_healthy
  whisper:
    build:
      context: .
      dockerfile: ./docker/whisper/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
  tts:
    build:
      context: ./docker/tts
    ports:
      - "5002:5002"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - tts_cache:/app/audio_cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  jarvis_logs:
  tts_cache:
