stt:
  docker_url: "http://localhost:5000/stt"
  timeout: 10
  language: "pt"
tts:
  docker_url: "http://localhost:5000/tts"
  voice: "default"
  offline: false
llm:
  model_path: "pierreguillou/gpt2-small-portuguese"
  max_tokens: 512
memory:
  db_path: "/app/memory/memory.db"
  user_id: "default"
executor:
  allowed_commands:
    - "notepad"
    - "calc"
    - "cmd.exe /c dir"
    - "firefox"
    - "vlc"
plugins:
  media_control:
    enabled: true
  weather_plugin:
    enabled: false
    api_key: ""
