version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jarvis-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - DATABASE_URL=sqlite:///./jarvis.db
      - REDIS_URL=redis://redis:6379
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./backend:/app
      - jarvis_data:/app/data
      - jarvis_logs:/app/logs
    depends_on:
      - redis
      - ollama
    restart: unless-stopped
    networks:
      - jarvis-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jarvis-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - jarvis-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: jarvis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - jarvis-network

  # Ollama for local LLM
  ollama:
    image: ollama/ollama:latest
    container_name: jarvis-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - jarvis-network

volumes:
  jarvis_data:
  jarvis_logs:
  redis_data:
  ollama_data:

networks:
  jarvis-network:
    driver: bridge